version: '3'

services:
  financeiro:    
    image: ricardo1782/financeiro-java
    ports:
      - '8080:8080'
    links: 
      - db
  db:
    image: mysql
    ports:
     - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=178209
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
  web-front:
    image: nginx
    ports:
      - '80:80'
    links:
      - financeiro
    volumes:
      - ./financas-front:/usr/share/nginx/html