version: '3'

services:
  financeiro:    
    image: financ
    ports:
      - '8080:8080'
    links: 
      - db
  db:
    image: mysql
    ports:
     - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=178209
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql